services:
  backend:
    build:
      context: ../project-taski
      dockerfile: ./backend/Dockerfile
    image: ju1ie/taski_backend
    container_name: taski_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*

  frontend:
    build:
      context: ../project-taski
      dockerfile: ./frontend/Dockerfile
    image: ju1ie/taski_frontend
    container_name: taski_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25-alpine
    network_mode: "host"
    build:
      context: ../project-taski
      dockerfile: ./nginx/Dockerfile
    container_name: taski_nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
    
