apiVersion: v1
kind: Service
metadata:
  name: taski-service
spec:
  selector:
    app: taski
  ports:
  - name: nginx
    port: 8080
    targetPort: 8080
  - name: frontend
    port: 3000
    targetPort: 3000
  - name: backend
    port: 8000
    targetPort: 8000
